"""Initial migration.

Revision ID: 11b254091c88
Revises: 
Create Date: 2022-07-30 11:33:16.128500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b254091c88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creditkons',
    sa.Column('month', sa.String(length=6), nullable=False),
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('credit_main', sa.BigInteger(), nullable=False),
    sa.Column('credit_interest', sa.BigInteger(), nullable=False),
    sa.Column('credit_total', sa.BigInteger(), nullable=False),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('status', sa.CHAR(length=1), nullable=False),
    sa.Column('created_by', sa.String(length=250), nullable=False),
    sa.Column('updated_by', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('month', 'nik')
    )
    op.create_table('creditprts',
    sa.Column('month', sa.String(length=6), nullable=False),
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('credit', sa.BigInteger(), nullable=False),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.Column('status', sa.CHAR(length=1), nullable=False),
    sa.Column('created_by', sa.String(length=250), nullable=False),
    sa.Column('updated_by', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('month', 'nik')
    )
    op.create_table('creditregs',
    sa.Column('month', sa.String(length=6), nullable=False),
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('credit_main', sa.BigInteger(), nullable=False),
    sa.Column('credit_interest', sa.BigInteger(), nullable=False),
    sa.Column('credit_total', sa.BigInteger(), nullable=False),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.Column('status', sa.CHAR(length=1), nullable=False),
    sa.Column('created_by', sa.String(length=250), nullable=False),
    sa.Column('updated_by', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('month', 'nik')
    )
    op.create_table('credits',
    sa.Column('id', sa.CHAR(length=3), nullable=False),
    sa.Column('desc', sa.String(length=250), nullable=False),
    sa.Column('interest', sa.Numeric(precision=2, scale=2), nullable=False),
    sa.Column('created_by', sa.String(length=250), nullable=False),
    sa.Column('updated_by', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salarys',
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('basic_salary', sa.BigInteger(), nullable=False),
    sa.Column('last_salary', sa.BigInteger(), nullable=True),
    sa.Column('last_month_pay', sa.String(length=6), nullable=True),
    sa.Column('created_by', sa.String(length=250), nullable=False),
    sa.Column('updated_by', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('nik')
    )
    op.create_table('savings',
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=6), nullable=False),
    sa.Column('date_save', sa.DateTime(), nullable=False),
    sa.Column('save_mand', sa.BigInteger(), nullable=True),
    sa.Column('save_main', sa.BigInteger(), nullable=True),
    sa.Column('save_volu', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.String(length=250), nullable=True),
    sa.Column('updated_by', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('nik', 'date_save', 'save_volu')
    )
    op.create_table('savings_masters',
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('save_mand', sa.BigInteger(), nullable=True),
    sa.Column('save_main', sa.BigInteger(), nullable=True),
    sa.Column('save_volu', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(length=250), nullable=True),
    sa.Column('updated_by', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('nik')
    )
    op.create_table('users',
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('no_hp', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('role', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.String(length=250), nullable=False),
    sa.Column('updated_by', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('nik', 'email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('savings_masters')
    op.drop_table('savings')
    op.drop_table('salarys')
    op.drop_table('credits')
    op.drop_table('creditregs')
    op.drop_table('creditprts')
    op.drop_table('creditkons')
    # ### end Alembic commands ###
