"""updated salarys

Revision ID: 3c5daeb1bc1b
Revises: 4b9628326c6c
Create Date: 2022-07-22 20:39:46.511376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5daeb1bc1b'
down_revision = '4b9628326c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salarys',
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('basic_salary', sa.BigInteger(), nullable=False),
    sa.Column('last_salary', sa.BigInteger(), nullable=True),
    sa.Column('last_month_pay', sa.String(length=6), nullable=True),
    sa.Column('created_by', sa.String(length=250), nullable=False),
    sa.Column('updated_by', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('nik')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salarys')
    # ### end Alembic commands ###
