"""updated users

Revision ID: 4b9628326c6c
Revises: 654e0a041cfa
Create Date: 2022-07-21 23:07:04.167940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9628326c6c'
down_revision = '654e0a041cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_by',
               existing_type=sa.VARCHAR(length=250, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('users', 'updated_by',
               existing_type=sa.VARCHAR(length=250, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_by',
               existing_type=sa.VARCHAR(length=250, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('users', 'created_by',
               existing_type=sa.VARCHAR(length=250, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    # ### end Alembic commands ###
