"""empty message

Revision ID: 4d1b8838dbf8
Revises: fd2543fd42d0
Create Date: 2022-07-25 20:08:26.717459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1b8838dbf8'
down_revision = 'fd2543fd42d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('savings', 'save_volu',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('savings', 'save_volu',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
