"""updated credits add

Revision ID: 5b66eda2727f
Revises: aa0d9ecdd1cc
Create Date: 2022-07-23 12:16:05.361964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b66eda2727f'
down_revision = 'aa0d9ecdd1cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creditkons', sa.Column('status', sa.CHAR(length=1), nullable=False))
    op.add_column('creditprts', sa.Column('status', sa.CHAR(length=1), nullable=False))
    op.add_column('creditregs', sa.Column('status', sa.CHAR(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creditregs', 'status')
    op.drop_column('creditprts', 'status')
    op.drop_column('creditkons', 'status')
    # ### end Alembic commands ###
