"""create users

Revision ID: 654e0a041cfa
Revises: 
Create Date: 2022-07-21 22:39:53.797758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654e0a041cfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('nik', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('no_hp', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('role', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.String(length=250), nullable=True),
    sa.Column('updated_by', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('nik', 'email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
