"""updated credits

Revision ID: aa0d9ecdd1cc
Revises: 3c5daeb1bc1b
Create Date: 2022-07-23 12:12:51.917573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0d9ecdd1cc'
down_revision = '3c5daeb1bc1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creditkons',
    sa.Column('month', sa.String(length=6), nullable=False),
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('credit_main', sa.BigInteger(), nullable=False),
    sa.Column('credit_interest', sa.BigInteger(), nullable=False),
    sa.Column('credit_total', sa.BigInteger(), nullable=False),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('created_by', sa.String(length=250), nullable=False),
    sa.Column('updated_by', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('month', 'nik')
    )
    op.create_table('creditprts',
    sa.Column('month', sa.String(length=6), nullable=False),
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('credit', sa.BigInteger(), nullable=False),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.String(length=250), nullable=False),
    sa.Column('updated_by', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('month', 'nik')
    )
    op.create_table('creditregs',
    sa.Column('month', sa.String(length=6), nullable=False),
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('credit_main', sa.BigInteger(), nullable=False),
    sa.Column('credit_interest', sa.BigInteger(), nullable=False),
    sa.Column('credit_total', sa.BigInteger(), nullable=False),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.String(length=250), nullable=False),
    sa.Column('updated_by', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('month', 'nik')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creditregs')
    op.drop_table('creditprts')
    op.drop_table('creditkons')
    # ### end Alembic commands ###
