"""updated savingsmaster create

Revision ID: b0a5f2c18b17
Revises: 424943a4d472
Create Date: 2022-07-24 12:47:38.627924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a5f2c18b17'
down_revision = '424943a4d472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings_masters',
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('save_mand', sa.BigInteger(), nullable=True),
    sa.Column('save_main', sa.BigInteger(), nullable=True),
    sa.Column('save_volu', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(length=250), nullable=True),
    sa.Column('updated_by', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('nik')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('savings_masters')
    # ### end Alembic commands ###
