"""change savings

Revision ID: c3cf97ce9871
Revises: 4d1b8838dbf8
Create Date: 2022-07-25 20:11:37.518789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3cf97ce9871'
down_revision = '4d1b8838dbf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings',
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=6), nullable=False),
    sa.Column('date_save', sa.DateTime(), nullable=False),
    sa.Column('save_mand', sa.BigInteger(), nullable=True),
    sa.Column('save_main', sa.BigInteger(), nullable=True),
    sa.Column('save_volu', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.String(length=250), nullable=True),
    sa.Column('updated_by', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('nik', 'date_save', 'save_volu')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('savings')
    # ### end Alembic commands ###
