"""change historys

Revision ID: c9829ba92f1b
Revises: 4b2cc37dfbbb
Create Date: 2022-08-01 22:31:13.512538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9829ba92f1b'
down_revision = '4b2cc37dfbbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nik', sa.String(length=20), nullable=True),
    sa.Column('start', sa.String(length=6), nullable=False),
    sa.Column('end', sa.String(length=6), nullable=False),
    sa.Column('credit', sa.BigInteger(), nullable=False),
    sa.Column('credit_type', sa.String(length=10), nullable=True),
    sa.Column('remarks', sa.String(length=250), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_history')
    # ### end Alembic commands ###
