"""updated savings

Revision ID: e081b0fbb208
Revises: 5b66eda2727f
Create Date: 2022-07-23 15:15:08.791741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e081b0fbb208'
down_revision = '5b66eda2727f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings',
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('date_save', sa.DateTime(), nullable=False),
    sa.Column('save_mand', sa.BigInteger(), nullable=True),
    sa.Column('save_main', sa.String(length=6), nullable=True),
    sa.Column('save_volu', sa.String(length=250), nullable=False),
    sa.Column('created_by', sa.String(length=250), nullable=True),
    sa.Column('updated_by', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('nik')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('savings')
    # ### end Alembic commands ###
