"""empty message

Revision ID: fd2543fd42d0
Revises: b0a5f2c18b17
Create Date: 2022-07-24 20:54:16.103244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2543fd42d0'
down_revision = 'b0a5f2c18b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings',
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=6), nullable=False),
    sa.Column('date_save', sa.DateTime(), nullable=False),
    sa.Column('save_mand', sa.BigInteger(), nullable=True),
    sa.Column('save_main', sa.BigInteger(), nullable=True),
    sa.Column('save_volu', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(length=250), nullable=True),
    sa.Column('updated_by', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('nik')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('savings')
    # ### end Alembic commands ###
